use_frameworks!

platform :ios, '8.0'

target 'SJFullscreenPopGesture_Example' do
  pod 'SJFullscreenPopGesture/ObjC', :path => '../'

  
  pod 'Masonry'
  pod 'SJTransitionAnimator'
  pod 'SJUIFactory'
  pod 'SJScrollEntriesView'

end
